server:
  port: 9096
spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jmyp_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 1000
      test-on-borrow: true
  jackson:
    date-format: yyyy:MM:dd
    time-zone: GMT+8
  redis:
    host: 192.168.66.66
    port: 6379
#  security:
#    user:
#      name: admin
#      password: admin
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
mybatis:
  type-aliases-package: com.jmyp.pojo
mapper:
  not-empty: false
  identity: mysql
jwt:
  config:
    key: czxy
    ttl: 60
hystrix:
  command:
    default:
        execution:
          isolation:
            thread:
              timeoutInMillisecond: 6000 # 熔断超时时长：6000ms